In [3]:
import numpy as np

## Array creation



In [6]:
x = [10, 52.5, 8998, 24]
x

[10, 52.5, 8998, 24]

In [8]:
y = np.array(x)
y

array([  10. ,   52.5, 8998. ,   24. ])

In [10]:
x = np.arrange(5)
x

array([0, 1, 2, 3, 4])

In [12]:
x = np.arange(10, 20, 2)   
x

array([10, 12, 14, 16, 18])

In [14]:
x = np.linspace(0, 1, 12)
x

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [20]:
x = np.full((5, 5)
x
# full
# zeros

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [21]:
x1 = np.random.randint(5, size=6)


array([3, 1, 4, 1, 0, 1])

## Array indexing



In [24]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
x[0]

10

In [27]:
x[-5]

15

In [28]:
x = np.arange(24).reshape((3,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
x[1, 1]

9

In [30]:
x[1]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
x[2][3]

19

In [32]:
x[-1]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [34]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [40]:
x[:2, 2: 6 : 2]

array([[ 2,  4],
       [10, 12]])

In [41]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Difference with Python

In [43]:
x = np.arange(24).reshape((3,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
y = x [:2, 2:4].copy
y

array([[ 2,  3],
       [10, 11]])

In [48]:
y[1, 1] = 1000
y

array([[   2,    3],
       [1000, 1000]])

## UFunc

In [52]:
x = [10.2, 1., 6.5, 2, 8, 10, 11, 100, 23]

rec = []

for i in x:
    rec.append(1./i)

rec

[0.09803921568627452,
 1.0,
 0.15384615384615385,
 0.5,
 0.125,
 0.1,
 0.09090909090909091,
 0.01,
 0.043478260869565216]

In [55]:
x = np.array(x)
y = 1./x
y

array([0.09803922, 1.        , 0.15384615, 0.5       , 0.125     ,
       0.1       , 0.09090909, 0.01      , 0.04347826])

## Aggregation

In [56]:
x = np.arange(1, 16).reshape((5, 3))
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [61]:
# np.sum(x)
np.sum(x, axis=1)


array([ 6, 15, 24, 33, 42])